# network architecture
# encoder related
etype: cnnblstm
elayers: 3
eunits: 512
dropout-rate: 0.2

# hybrid CTC/attention, this is set to deactivate ploting acc figures
mtlalpha: 1.0

# minibatch related
batch-size: 30
maxlen-in: 800  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: adadelta
epochs: 30
patience: 3

# label smoothing option
lsm-weight: 0.0

backend: pytorch
model-module: "espnet.nets.pytorch_backend.e2e_lid_lstm:E2E"



